class Foo;
class Bar;
struct Baz;
typedef Plain<Foo> p;
typedef Ref<Bar*> r;
typedef Baz* b;
typedef int Type;
typedef int& reference;
typedef int (*pf1)(int, int);
typedef int (&pf2)(int, int);
typedef int pf3();
